banking_insights:
  outputs:
    dev:
      account: DUTFEHS-EM46938
      database: banking_db
      password: Anasbendahmen001$
      role: rl_dbt
      schema: raw
      threads: 2
      type: snowflake
      user: MCLOVIN
      warehouse: banking_warehouse
  target: dev
